export const GET_CATEGORIES = 'GET_CATEGORIES'
export const ADD_CATEGORIES = 'ADD_CATEGORIES'

export const GET_TRANSACTIONS = 'GET_TRANSACTIONS'
export const ADD_TRANSACTION = 'ADD_TRANSACTION'
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION'
export const UPDATE_TRANSACTION = 'UPDATE_TRANSACTION'