export const GET_CATEGORIES = 'GET_CATEGORIES'
export const ADD_CATEGORIES = 'ADD_CATEGORIES'

export const GET_TRANSACTIONS = 'GET_TRANSACTIONS'
export const ADD_TRANSACTIONS = 'ADD_TRANSACTIONS'

// export const GET_TRANSACDATE = 'GET_TRANSACDATE'